{
  "issue_number": 12515,
  "title": "log backup checkpoint_ts get smaller than gc_safepoint",
  "body": "## Bug Report\r\n\r\n<!-- Thanks for your bug report! Don't worry if you can't fill out all the sections. -->\r\n\r\n### What version of TiKV are you using?\r\nv6.1.0-alpha-nightly-20220513\r\n\r\n### What operating system and CPU are you using?\r\nCentOS 16U\r\n\r\n### Steps to reproduce\r\n1. Start a log backup task,\r\n2. There is one TiKV  continuously OOM \r\n3. Check log status, checkpoint_ts global is: 2022-05-13 19:45:00 +0800\r\n```\r\n11:46:06 root@172 fubin → tiup br:v6.1.0-alpha-nightly-20220514 log status --pd 172.16.5.74:2379\r\nStarting component `br`: /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br log status --pd 172.16.5.74:2379\r\nDetail BR log in /tmp/br.log.2022-05-14T11.46.24+0800\r\n● Total 1 Tasks.\r\n> #1 <\r\n               name: test4\r\n             status: ● NORMAL\r\n              start: 2022-05-13 19:45:00 +0800 CST\r\n                end: 2035-01-01 00:00:00 +0800 CST\r\n            storage: s3://nfs/fubin/pitr/pp_log_4\r\n        speed(est.): 0.00 ops/s\r\n checkpoint[global]: 2022-05-13 19:45:00 +0800 CST; gap=16h1m26s\r\ncheckpoint[store=5]: 2022-05-13 19:45:00 +0800 CST; gap=16h1m26s\r\ncheckpoint[store=6]: 2022-05-13 19:45:00 +0800 CST; gap=16h1m26s\r\ncheckpoint[store=1]: 2022-05-13 19:45:00 +0800 CST; gap=16h1m26s\r\ncheckpoint[store=4]: 2022-05-13 19:45:00 +0800 CST; gap=16h1m26s\r\n\r\n```\r\n\r\n### What did you expect?\r\nlog backup checkpoint ts should not be GCed.\r\n\r\n### What did happened?\r\nlog backup checkpoint ts is be GCed, which result in task error, I can't pause the task.\r\n\r\n```\r\n11:46:26 root@172 fubin → tiup br:v6.1.0-alpha-nightly-20220514 log pause --pd 172.16.5.74:2379 --task-id test4\r\nStarting component `br`: /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br log pause --pd 172.16.5.74:2379 --task-id test4\r\nError: unknown flag: --task-id\r\n[2022/05/14 11:46:39.423 +08:00] [ERROR] [main.go:59] [\"br failed\"] [error=\"unknown flag: --task-id\"] [stack=\"main.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:59\\nrunti\r\nme.main\\n\\t/usr/local/go/src/runtime/proc.go:250\"]\r\n11:46:39 root@172 fubin → tiup br:v6.1.0-alpha-nightly-20220514 log pause --pd 172.16.5.74:2379 --task-name test4\r\nStarting component `br`: /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br /root/.tiup/components/br/v6.1.0-alpha-nightly-20220514/br log pause --pd 172.16.5.74:2379 --task-name test4\r\nDetail BR log in /tmp/br.log.2022-05-14T11.46.46+0800\r\n[2022/05/14 11:46:48.552 +08:00] [INFO] [collector.go:69] [\"log pause failed summary\"] [total-ranges=1] [ranges-succeed=0] [ranges-failed=1] [unit-name=\"log pause\"] [error=\"failed to check gc safePoint, checkpoint ts 43317\r\n7834291200000: GC safepoint 433192620449595392 exceed TS 433177834291200000: [BR:Backup:ErrBackupGCSafepointExceeded]backup GC safepoint exceeded\"] [errorVerbose=\"[BR:Backup:ErrBackupGCSafepointExceeded]backup GC safepoint\r\n exceeded\\nGC safepoint 433192620449595392 exceed TS 433177834291200000\\ngithub.com/pingcap/tidb/br/pkg/utils.CheckGCSafePoint\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/safe_po\r\nint.go:74\\ngithub.com/pingcap/tidb/br/pkg/task.(*streamMgr).setGCSafePoint\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:354\\ngithub.com/pingcap/tidb/br/pkg/task.RunStream\r\nPause\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:653\\ngithub.com/pingcap/tidb/br/pkg/task.RunStreamCommand\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.c\r\nom/pingcap/br/br/pkg/task/stream.go:480\\nmain.streamCommand\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/stream.go:189\\nmain.newStreamPauseCommand.func1\\n\\t/home/jenkins/agent/worksp\r\nace/build-common/go/src/github.com/pingcap/br/br/cmd/br/stream.go:96\\ngithub.com/spf13/cobra.(*Command).execute\\n\\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\\ngithub.com/spf13/cobra.(*Command).ExecuteC\\n\\t/go\r\n/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\\ngithub.com/spf13/cobra.(*Command).Execute\\n\\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/g\r\nithub.com/pingcap/br/br/cmd/br/main.go:57\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250\\nruntime.goexit\\n\\t/usr/local/go/src/runtime/asm_amd64.s:1571\\nfailed to check gc safePoint, checkpoint ts 433177834291200000\r\n\"]\r\nError: failed to check gc safePoint, checkpoint ts 433177834291200000: GC safepoint 433192620449595392 exceed TS 433177834291200000: [BR:Backup:ErrBackupGCSafepointExceeded]backup GC safepoint exceeded\r\n11:46:48 root@172 fubin → tiup ctl:v6.0.0 pd tso 433177834291200000\r\nStarting component `ctl`: /root/.tiup/components/ctl/v6.0.0/ctl /root/.tiup/components/ctl/v6.0.0/ctl pd tso 433177834291200000\r\nsystem:  2022-05-13 19:45:00 +0800 CST\r\nlogic:   0\r\n11:47:32 root@172 fubin → tiup ctl:v6.0.0 pd tso 433192620449595392\r\nStarting component `ctl`: /root/.tiup/components/ctl/v6.0.0/ctl /root/.tiup/components/ctl/v6.0.0/ctl pd tso 433192620449595392\r\nsystem:  2022-05-14 11:25:04.718 +0800 CST\r\nlogic:   0\r\n\r\n```\r\n\r\n",
  "state": "closed",
  "created_at": "2022-05-14T09:43:17Z",
  "updated_at": "2022-05-14T10:49:08Z",
  "closed_at": "2022-05-14T10:49:08Z",
  "labels": [
    "type/bug",
    "severity/major",
    "feature/developing"
  ],
  "comments_data": [
    {
      "id": 1126681339,
      "user": "fubinzh",
      "created_at": "2022-05-14T09:44:07Z",
      "body": "/type bug\r\n/severity Major\r\n/feature developing"
    },
    {
      "id": 1126689985,
      "user": "3pointer",
      "created_at": "2022-05-14T10:49:08Z",
      "body": "The first time start task is \r\n`[2022/05/13 20:59:45.753 +08:00] [INFO] [stream.go:372] [\"set stream safePoint\"] [safePoint=\"{ID=br-b0d3cebd-07dc-4b72-8b36-a4d51fae702f,TTL=5m0s,BackupTime=\\\"2022-05-13 19:45:00 +0800 CST\\\",BackupTS=433177834291200000}\"]`\r\n\r\nAnd first time TiKV received flushing task is \r\n`\r\n[2022/05/13 21:03:10.095 +08:00] [INFO] [endpoint.rs:558] [\"flushing and refreshing checkpoint ts.\"] [task=test4] [checkpoint_ts=433177834291200000]\r\n`\r\n\r\nwe found TiKV starts to OOM due to https://github.com/tikv/tikv/issues/12509 between [20:30, 22:00]\r\n<img width=\"1378\" alt=\"image\" src=\"https://user-images.githubusercontent.com/5906259/168422447-b7d26020-3538-4c17-912d-fbcd429aa5e2.png\">\r\n\r\n\r\nand in this situation tikv won't be able to send update_gc_service_point to PD. that cause the GC advanced finally.\r\n\r\nwe can also see tikv wasn't send any requests to PD.\r\n<img width=\"1372\" alt=\"截屏2022-05-14 下午6 43 53\" src=\"https://user-images.githubusercontent.com/5906259/168422503-71f3a1be-3085-4689-948b-426525dedc24.png\">\r\n\r\nSo, I think this is abnormal situation, This issue will fixed when https://github.com/tikv/tikv/issues/12509  closed.\r\n\r\n\r\n"
    }
  ]
}