{
  "issue_number": 15022,
  "title": "[Dynamic Regions] br restore checksum failure on v2",
  "body": "## Bug Report\r\n\r\n<!-- Thanks for your bug report! Don't worry if you can't fill out all the sections. -->\r\n\r\n### What version of TiKV are you using?\r\n<!-- You can run `tikv-server --version` -->\r\nmaster\r\n\r\n### What operating system and CPU are you using?\r\n<!-- If you're using Linux, you can run `cat /proc/cpuinfo` -->\r\n\r\n\r\n### Steps to reproduce\r\n<!-- If possible, provide a recipe for reproducing the error. A complete runnable program is good. -->\r\n```\r\n[2023/06/27 13:15:59.098 +08:00] [INFO] [utils.go:692] [\"   tiup br:nightly restore db --db=gharchive--pd \\\"pd-peer.release-perftest-arm64-ddl-ossinsight-001-tps-1812652-1-808:2379\\\" \\\\\\n        --storage \\\"s3://ossinsight-2tiflash\\\" \\\\\\n        --s3.endpoint \\\"http://xxx\\\" \\\\\\n        --send-credentials-to-tikv=true \\\\\\n\\t\\t--check-requirements=false --checksum-concurrency 128\"]\r\n```\r\n\r\n\r\n### What did you expect?\r\nno checksum error\r\n\r\n\r\n### What did happened?\r\n\r\n```\r\n\r\nDataBase Restore <-----------------------------------.......................................> 46.87%DataBase Restore <-------------------------------------------------------------------------> 100.00%Error: other error: Coprocessor task terminated due to exceeding the deadline;```\r\n",
  "state": "closed",
  "created_at": "2023-06-28T03:55:26Z",
  "updated_at": "2023-07-07T06:12:24Z",
  "closed_at": "2023-07-07T06:12:24Z",
  "labels": [
    "type/bug",
    "severity/major",
    "feature/developing"
  ],
  "comments_data": []
}