{
  "bug_location": "Unknown",
  "severity": 3,
  "categories": [
    "Unknown"
  ],
  "root_cause": "N/A - Analysis failed",
  "issue_number": 5239,
  "title": "util::tests::test_delete_all_files_in_range can fail"
}